name: Get Citation Data

on:
  workflow_dispatch:
  page_build:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run crawler
        run: |
          cd ./google_scholar_crawler
          pip install -r requirements.txt
          python main.py
          cd ./results
          git init
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add *.json
          git commit -m "Updated Citation Data"
          git push "${remote_repo}" HEAD:google-scholar-stats --force
        env:
          GOOGLE_SCHOLAR_ID: XqQp-fkAAAAJ
          GITHUB_USERNAME: lgy0404
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
